#!/usr/bin/env node
// Rewrites generate.js's mechanical draft SKILL.md files into agent-directed
// guidance, via `claude -p`. Deliberately a separate step from `npm run
// generate`: generate.js must stay deterministic and idempotent (#217's own
// acceptance criteria), but an LLM rewrite is neither of those things - so
// this is an explicit, visible action you run when a skill's source has
// actually changed, never a silent side effect of installing or generating.
//
// Skips a skill whose mapped source docs haven't changed since it was last
// polished (tracked in .polish-manifest.json), so bumping the pin doesn't
// re-roll wording - or spend an API call - on skills nothing changed in.
'use strict';

const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const { execFileSync } = require('child_process');
const { SKILL_MAP, SKILLS_DIR, MANIFEST_PATH, PLUGIN_ROOT } = require('./generate.js');

const POLISH_MANIFEST_PATH = path.join(PLUGIN_ROOT, '.polish-manifest.json');

function sha256(text) {
  return crypto.createHash('sha256').update(text, 'utf8').digest('hex');
}

// A skill's "polish key" is derived from its mapped source files' content
// hashes (already computed by generate.js into .docs-manifest.json) rather
// than rehashing the docs directly - reuses work generate.js already did,
// and changes exactly when generate.js's own drift-relevant inputs change.
function polishKey(skill, docsManifest) {
  const hashes = skill.sources.map((f) => docsManifest.files[f]);
  return sha256(hashes.join('|'));
}

function buildPrompt(skillName, rawMarkdown) {
  return `You are editing a Claude Code skill file (SKILL.md) that was mechanically generated by concatenating source documentation. Rewrite it in agent-directed, imperative voice while preserving every fact and every link exactly.

## Rules — follow all of them

1. Keep the YAML frontmatter's "name", "license", and "metadata" fields byte-for-byte unchanged. You MAY rewrite the "description" field to be more specific about when to trigger this skill (mention concrete situations or phrasings a user might use) — descriptions should be a little "pushy" so the skill isn't under-triggered.
2. Preserve every markdown link and image URL in the body EXACTLY, character for character, including the attribution blockquote line right after the frontmatter. Do not add, remove, or alter any URL.
3. Do not invent new advice, facts, or examples that aren't already present in the source content. Do not drop any substantive point that IS present — condensing repeated wording for concision is fine, dropping information is not.
4. Rewrite the body's voice: from prose describing a topic to a human reader, into direct guidance addressed to an AI coding agent about to take action. Prefer imperative form ("When doing X, do Y because Z") over descriptive form ("X is a technique that..."). Explain the WHY behind a recommendation rather than just asserting it. Example of the shift:

   BEFORE: "Unit tests are the smallest tests you can write. They test individual parts of your application in isolation... They are fast to run and easy to write."
   AFTER: "Reach for these to isolate a single complex function, or a shared component/utility used throughout the app. Fast and cheap to write, but passing unit tests alone don't prove the app actually works end to end."

5. Keep the same overall structure (headings, code blocks) unless reorganizing genuinely improves clarity. Keep it roughly the same length — this is a voice/structure pass, not a rewrite that adds bulk.
6. Output ONLY the final, complete SKILL.md file content (frontmatter included) — no commentary, no explanation, no markdown code fence wrapping the whole output.

## Skill name

${skillName}

## Current content to rewrite

${rawMarkdown}`;
}

function polishSkill(skill, rawMarkdown) {
  const prompt = buildPrompt(skill.name, rawMarkdown);
  return execFileSync('claude', ['-p', prompt], {
    encoding: 'utf8',
    maxBuffer: 10 * 1024 * 1024,
  }).trim() + '\n';
}

function main() {
  if (!fs.existsSync(MANIFEST_PATH)) {
    throw new Error(
      `${path.basename(MANIFEST_PATH)} not found — run \`npm run generate\` first.`
    );
  }
  const docsManifest = JSON.parse(fs.readFileSync(MANIFEST_PATH, 'utf8'));

  let polishManifest = { polished: {} };
  if (fs.existsSync(POLISH_MANIFEST_PATH)) {
    polishManifest = JSON.parse(fs.readFileSync(POLISH_MANIFEST_PATH, 'utf8'));
  }

  let polished = 0;
  let skipped = 0;

  for (const skill of SKILL_MAP) {
    const skillPath = path.join(SKILLS_DIR, skill.name, 'SKILL.md');
    if (!fs.existsSync(skillPath)) {
      console.warn(`⚠ ${skill.name}: no generated SKILL.md found — run \`npm run generate\` first`);
      continue;
    }

    const key = polishKey(skill, docsManifest);
    if (polishManifest.polished[skill.name] === key) {
      console.log(`= ${skill.name}: already polished against current source, skipping`);
      skipped++;
      continue;
    }

    console.log(`… polishing ${skill.name} (calling \`claude -p\`)...`);
    const rawMarkdown = fs.readFileSync(skillPath, 'utf8');
    fs.writeFileSync(skillPath, polishSkill(skill, rawMarkdown));
    polishManifest.polished[skill.name] = key;
    console.log(`✓ polished skills/${skill.name}/SKILL.md`);
    polished++;
  }

  fs.writeFileSync(POLISH_MANIFEST_PATH, JSON.stringify(polishManifest, null, 2) + '\n');
  console.log(`\n${polished} polished, ${skipped} already up to date.`);
  if (polished > 0) {
    console.log('Review each polished SKILL.md against its source before committing.');
  }
}

main();
