#!/usr/bin/env node
// Rewrites generate.js's mechanical draft SKILL.md files into agent-directed
// guidance, via `claude -p`. Deliberately a separate step from `npm run
// generate`: generate.js must stay deterministic and idempotent (#217's own
// acceptance criteria), but an LLM rewrite is neither of those things - so
// this is an explicit, visible action you run when a skill's source has
// actually changed, never a silent side effect of installing or generating.
//
// Skips a skill whose mapped source docs haven't changed since it was last
// polished (tracked in .polish-manifest.json), so bumping the pin doesn't
// re-roll wording - or spend an API call - on skills nothing changed in.
'use strict';

const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const { execFileSync } = require('child_process');
const { SKILL_MAP, SKILLS_DIR, MANIFEST_PATH, PLUGIN_ROOT } = require('./generate.js');

const POLISH_MANIFEST_PATH = path.join(PLUGIN_ROOT, '.polish-manifest.json');

function sha256(text) {
  return crypto.createHash('sha256').update(text, 'utf8').digest('hex');
}

// A skill's "polish key" is derived from its mapped source files' content
// hashes (already computed by generate.js into .docs-manifest.json) rather
// than rehashing the docs directly - reuses work generate.js already did,
// and changes exactly when generate.js's own drift-relevant inputs change.
function polishKey(skill, docsManifest) {
  const hashes = skill.sources.map((f) => docsManifest.files[f]);
  return sha256(hashes.join('|'));
}

function buildPrompt(skillName, rawMarkdown) {
  return `You are editing a Claude Code skill file (SKILL.md) that was mechanically generated by concatenating source documentation. Rewrite it in agent-directed, imperative voice while preserving every fact and every link exactly.

## Rules — follow all of them

1. Keep the YAML frontmatter's "name", "license", and "metadata" fields byte-for-byte unchanged. You MUST rewrite the "description" field, even if the current one already looks reasonable to you — it needs to be longer and more specific, not just acceptable. Concretely: it MUST end with a sentence listing 3 or more specific situations or phrasings a user might actually type (in quotes), not just a one-line topic summary. This is a hard, checkable requirement, separate from rule 5's "keep it roughly the same length" — that rule is about the body, and does not apply to the description. Example of the shift:

   BEFORE: "Testing conventions from bulletproof-react: unit/integration/e2e test types and MSW. Use when adding tests to a React app."
   AFTER: "Testing strategy conventions from bulletproof-react: when to reach for a unit vs. integration vs. e2e test, and the recommended tooling (Vitest, Testing Library, Playwright, MSW) for each. Use this whenever adding tests to a React app, deciding what kind of test a piece of code actually needs, or reviewing a PR's test coverage — especially when the default has been "add a unit test" without considering whether an integration test would give more real confidence."
2. Preserve every markdown link and image URL in the body EXACTLY, character for character, including the attribution blockquote line right after the frontmatter. Do not add, remove, or alter any URL.
3. Do not invent new advice, facts, or examples that aren't already present in the source content. Do not drop any substantive point that IS present — condensing repeated wording for concision is fine, dropping information is not.
4. Rewrite the body's voice: from prose describing a topic to a human reader, into direct guidance addressed to an AI coding agent about to take action. Prefer imperative form ("When doing X, do Y because Z") over descriptive form ("X is a technique that..."). Explain the WHY behind a recommendation rather than just asserting it. Example of the shift:

   BEFORE: "Unit tests are the smallest tests you can write. They test individual parts of your application in isolation... They are fast to run and easy to write."
   AFTER: "Reach for these to isolate a single complex function, or a shared component/utility used throughout the app. Fast and cheap to write, but passing unit tests alone don't prove the app actually works end to end."

5. Keep the same overall structure (headings, code blocks) unless reorganizing genuinely improves clarity. Keep it roughly the same length — this is a voice/structure pass, not a rewrite that adds bulk.
6. Output ONLY the final, complete SKILL.md file content (frontmatter included) — no commentary, no explanation, no markdown code fence wrapping the whole output.

## Skill name

${skillName}

## Current content to rewrite

${rawMarkdown}

## Before you output

Compare the description you're about to output, word for word, against the "description" block above. If it's the same or nearly the same, you have not done rule 1 — go back and actually rewrite it to be more specific and pushier before responding.`;
}

// Every markdown/image link target in `markdown` (order-independent set) -
// used to verify the polish pass didn't drop one. Mirrors the link pattern
// generate.js's rewriteRelativeLinks already matches.
function linkTargets(markdown) {
  const targets = new Set();
  const re = /!?\[[^\]]*\]\(([^)]+)\)/g;
  let match;
  while ((match = re.exec(markdown))) {
    targets.add(match[1]);
  }
  return targets;
}

// Pulls the raw text of the "description: |" block scalar out of a SKILL.md's
// frontmatter — everything indented under it, up to the next top-level key
// (or the closing "---"). Used only to compare before/after, so it doesn't
// need to be a real YAML parser, just consistent between two calls on the
// same file shape.
function descriptionBlock(markdown) {
  const match = markdown.match(/^description:\s*\|\n((?:[ \t].*\n?|\n)*)/m);
  return match ? match[1].trim() : null;
}

const MAX_ATTEMPTS = 3;

function polishSkill(skill, rawMarkdown) {
  const prompt = buildPrompt(skill.name, rawMarkdown);
  const rawLinks = linkTargets(rawMarkdown);
  const rawDescription = descriptionBlock(rawMarkdown);
  let lastError;

  for (let attempt = 1; attempt <= MAX_ATTEMPTS; attempt++) {
    // --tools '' strips all tool access from this subprocess. Without it,
    // claude -p can behave as a full agent rather than a pure text
    // completion - observed firsthand: it attempted a Write tool call
    // (apparently reading "SKILL.md" in the prompt as an instruction to
    // edit a real file), which needs interactive permission a
    // non-interactive `-p` call can't give, and its "waiting for your
    // approval" message came back as stdout and got written into the skill
    // file as if it were the rewritten content. Must come after the prompt
    // argument - placed before it, `--tools`'s variadic arg parsing
    // swallows the prompt as part of the tools list.
    const result = execFileSync('claude', ['-p', prompt, '--tools', ''], {
      encoding: 'utf8',
      maxBuffer: 10 * 1024 * 1024,
    }).trim();

    // Defense in depth alongside --tools '': refuse to write anything that
    // doesn't look like a real SKILL.md rather than trusting the subprocess
    // output blindly - the exact failure mode above produced a plausible-
    // looking single line of prose with a clean (0) exit code, so "it
    // didn't throw" isn't sufficient evidence the output is safe to write.
    if (!result.startsWith('---\n') && !result.startsWith('---\r\n')) {
      lastError = new Error(
        `claude -p's output doesn't start with a frontmatter delimiter ("---"). ` +
          `Got:\n${result.slice(0, 300)}`
      );
      continue;
    }

    // The prompt explicitly says "preserve every link exactly," but this is
    // non-deterministic: observed firsthand that a rewrite can still
    // consolidate a bulleted list into prose and drop the per-item links in
    // the process, on a re-run of the very same skill that preserved them
    // correctly the first time. Checking the actual output beats trusting
    // the instruction was followed - retry once before giving up, since a
    // second sample from the same prompt is cheap and often succeeds where
    // the first didn't.
    const missing = [...rawLinks].filter((l) => !linkTargets(result).has(l));
    if (missing.length > 0) {
      lastError = new Error(
        `claude -p dropped ${missing.length} link(s) present in the source:\n` +
          missing.map((l) => `  - ${l}`).join('\n')
      );
      continue;
    }

    // Rule 1 says the description MUST be rewritten with 3+ quoted example
    // phrasings, but "must" in a prompt is a request, not a guarantee -
    // observed firsthand that a run can leave every one of 7 descriptions
    // byte-identical to the input despite the instruction, silently
    // skipping the one part of the pass that's supposed to happen every
    // time (it's the main lever against under-triggering, per the
    // skill-creator guidance this prompt is built from). Checking for the
    // concrete, checkable part of rule 1 (quoted phrasings present, content
    // actually changed) can't confirm the rewrite is well-written, only
    // that it was actually attempted along the lines asked for - good
    // enough to catch the observed failure mode without trying to grade
    // prose quality mechanically.
    const newDescription = descriptionBlock(result);
    const quotedPhrases = (newDescription.match(/["“][^"”]{3,}["”]/g) || []).length;
    if (newDescription === rawDescription || quotedPhrases < 2) {
      lastError = new Error(
        'claude -p did not rewrite the description with the required quoted example ' +
          `phrasings (found ${quotedPhrases}, need at least 2).`
      );
      continue;
    }

    return result + '\n';
  }

  throw new Error(`${skill.name}: ${lastError.message} (after ${MAX_ATTEMPTS} attempts)`);
}

function main() {
  if (!fs.existsSync(MANIFEST_PATH)) {
    throw new Error(
      `${path.basename(MANIFEST_PATH)} not found — run \`npm run generate\` first.`
    );
  }
  const docsManifest = JSON.parse(fs.readFileSync(MANIFEST_PATH, 'utf8'));

  let polishManifest = { polished: {} };
  if (fs.existsSync(POLISH_MANIFEST_PATH)) {
    polishManifest = JSON.parse(fs.readFileSync(POLISH_MANIFEST_PATH, 'utf8'));
  }

  let polished = 0;
  let skipped = 0;

  for (const skill of SKILL_MAP) {
    const skillPath = path.join(SKILLS_DIR, skill.name, 'SKILL.md');
    if (!fs.existsSync(skillPath)) {
      console.warn(`⚠ ${skill.name}: no generated SKILL.md found — run \`npm run generate\` first`);
      continue;
    }

    const key = polishKey(skill, docsManifest);
    if (polishManifest.polished[skill.name] === key) {
      console.log(`= ${skill.name}: already polished against current source, skipping`);
      skipped++;
      continue;
    }

    console.log(`… polishing ${skill.name} (calling \`claude -p\`)...`);
    const rawMarkdown = fs.readFileSync(skillPath, 'utf8');
    fs.writeFileSync(skillPath, polishSkill(skill, rawMarkdown));
    polishManifest.polished[skill.name] = key;
    // Written after every skill, not once at the end: polishSkill throws on
    // an unrecoverable failure (see MAX_ATTEMPTS), and without this, a
    // failure on skill N would lose the manifest entries for the 1..N-1
    // skills that already succeeded - their SKILL.md files would be
    // correctly polished on disk, but a re-run wouldn't know that and would
    // spend an API call re-polishing them anyway.
    fs.writeFileSync(POLISH_MANIFEST_PATH, JSON.stringify(polishManifest, null, 2) + '\n');
    console.log(`✓ polished skills/${skill.name}/SKILL.md`);
    polished++;
  }

  console.log(`\n${polished} polished, ${skipped} already up to date.`);
  if (polished > 0) {
    console.log('Review each polished SKILL.md against its source before committing.');
  }
}

main();
